[[actions]]
name = "play"
platform = "windows"
path = "Awoogen/Awoogen.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "Awoogen/Awoogen"
args = ["--launched-through-itch"]
